"""
CareerPilot AI - Email Automation Bot Module
Generates daily PDF & CSV reports and dispatches automated updates via SMTP.
"""

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from datetime import datetime
from pathlib import Path
from config import REPORTS_DIR, logger
from database import db_manager
from models import Job, Application, Settings
from utils import export_jobs_to_pdf, export_jobs_to_csv


class EmailBot:
    """Automated email report generator and SMTP dispatcher."""

    def __init__(self):
        self.reports_dir = REPORTS_DIR

    def generate_daily_report_files(self) -> tuple[str, str]:
        """Generate PDF report and CSV attachment for today's summary."""
        session = db_manager.get_session()
        try:
            jobs = session.query(Job).order_by(Job.id.desc()).all()
            jobs_dicts = [j.to_dict() for j in jobs]

            today_str = datetime.now().strftime("%Y_%m_%d")
            pdf_path = str(REPORTS_DIR / f"CareerPilot_Daily_Report_{today_str}.pdf")
            csv_path = str(REPORTS_DIR / f"CareerPilot_Jobs_{today_str}.csv")

            # Export files
            export_jobs_to_pdf(jobs_dicts, output_path=pdf_path, title=f"CareerPilot Daily Job & Application Summary ({today_str})")
            export_jobs_to_csv(jobs_dicts, output_path=csv_path)

            return pdf_path, csv_path
        finally:
            session.close()

    def send_daily_email(self, recipient_email: str = None) -> bool:
        """Send daily summary report with attachments via SMTP."""
        session = db_manager.get_session()
        try:
            settings = session.query(Settings).first()
            if not settings or not settings.email:
                logger.warning("No recipient email configured in settings.")
                target_email = recipient_email or "candidate@careerpilot.ai"
            else:
                target_email = recipient_email or settings.email

            total_jobs = session.query(Job).count()
            total_apps = session.query(Application).count()
            interviews = session.query(Application).filter(Application.status == "Interview").count()

            pdf_file, csv_file = self.generate_daily_report_files()

            # Construct MIME Email
            msg = MIMEMultipart()
            msg["From"] = settings.smtp_username if settings and settings.smtp_username else "notifications@careerpilot.ai"
            msg["To"] = target_email
            msg["Subject"] = f"CareerPilot Daily Report - {datetime.now().strftime('%B %d, %Y')}"

            html_body = f"""
            <html>
            <body style="font-family: Arial, sans-serif; background-color: #0f172a; color: #f8fafc; padding: 20px;">
                <div style="max-width: 600px; margin: 0 auto; background-color: #1e293b; padding: 25px; border-radius: 10px; border: 1px solid #334155;">
                    <h2 style="color: #38bdf8;">✈️ CareerPilot AI - Daily Executive Summary</h2>
                    <p>Here is your automated job search and application activity report for <strong>{datetime.now().strftime('%A, %B %d, %Y')}</strong>.</p>
                    
                    <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
                        <tr style="background-color: #0f172a;">
                            <td style="padding: 12px; border: 1px solid #334155;"><strong>Total Jobs Tracked:</strong></td>
                            <td style="padding: 12px; border: 1px solid #334155; color: #38bdf8; font-weight: bold;">{total_jobs}</td>
                        </tr>
                        <tr>
                            <td style="padding: 12px; border: 1px solid #334155;"><strong>Applications Sent:</strong></td>
                            <td style="padding: 12px; border: 1px solid #334155; color: #60a5fa; font-weight: bold;">{total_apps}</td>
                        </tr>
                        <tr style="background-color: #0f172a;">
                            <td style="padding: 12px; border: 1px solid #334155;"><strong>Upcoming Interviews:</strong></td>
                            <td style="padding: 12px; border: 1px solid #334155; color: #f59e0b; font-weight: bold;">{interviews}</td>
                        </tr>
                    </table>
                    
                    <p style="color: #94a3b8; font-size: 13px;">Attached to this email you will find the complete <strong>PDF Daily Report</strong> and <strong>CSV Export</strong> containing all current job listings and application notes.</p>
                    
                    <p style="margin-top: 25px; border-top: 1px solid #334155; padding-top: 15px; font-size: 12px; color: #64748b;">
                        Generated by CareerPilot AI Platform. To modify email schedules or SMTP credentials, visit the Settings tab in your app.
                    </p>
                </div>
            </body>
            </html>
            """
            msg.attach(MIMEText(html_body, "html"))

            # Attach PDF File
            if Path(pdf_file).exists():
                with open(pdf_file, "rb") as f:
                    part = MIMEApplication(f.read(), _subtype="pdf")
                    part.add_header("Content-Disposition", "attachment", filename=Path(pdf_file).name)
                    msg.attach(part)

            # Attach CSV File
            if Path(csv_file).exists():
                with open(csv_file, "rb") as f:
                    part = MIMEApplication(f.read(), _subtype="csv")
                    part.add_header("Content-Disposition", "attachment", filename=Path(csv_file).name)
                    msg.attach(part)

            # Check if SMTP details are configured
            if settings and settings.smtp_server and settings.smtp_username and settings.smtp_password:
                try:
                    server = smtplib.SMTP(settings.smtp_server, settings.smtp_port)
                    server.starttls()
                    server.login(settings.smtp_username, settings.smtp_password)
                    server.sendmail(msg["From"], target_email, msg.as_string())
                    server.quit()
                    logger.info(f"Daily report email successfully sent to {target_email}.")
                    return True
                except Exception as smtp_err:
                    logger.error(f"SMTP authentication or dispatch error: {smtp_err}")
                    logger.info(f"Generated email report saved locally at {pdf_file}")
                    return True
            else:
                logger.info(f"SMTP credentials not fully set. Report generated and saved locally at {pdf_file}")
                return True

        except Exception as e:
            logger.error(f"Error executing daily email dispatch: {e}", exc_info=True)
            return False
        finally:
            session.close()


# Singleton instance helper
email_bot = EmailBot()
